const express = require('express');
const router = express.Router();

router.get('/', (req, res, next) => {
	res.status(200).json({
		message: 'Succsess',
		data: [
			{
				city: 'Jerusalem',
				neighborhood: 'Baka',
				apartmentNumber: 1,
				room: 9,
				price: 4425000,
				sqrM: 1200,
				floor: '4 / 6',
				balconies: 2,
				parking: 4,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Baka/b_apartment1/bedroom-2631746_b.jpg',
					'images/apartments/Baka/b_apartment1/black-fabric-sofa-near-round-white-table-813691_b.jpg',
					'images/apartments/Baka/b_apartment1/bookcase-chair-computer-contemporary-263209_b.jpg',
					'images/apartments/Baka/b_apartment1/brown-and-black-stairs-3258311_b.jpg',
					'images/apartments/Baka/b_apartment1/brown-wooden-baby-crib-near-white-wooden-framed-glass-window-3958952_b.jpg',
					'images/apartments/Baka/b_apartment1/dining-room-4320372_b.jpg',
					'images/apartments/Baka/b_apartment1/green-leafed-plants-on-kitchen-island-1358900_b.jpg',
					'images/apartments/Baka/b_apartment1/apartment-comfort-contemporary-decor-271800_b.jpg',
					'images/apartments/Baka/b_apartment1/bed-bedroom-chair-comfort-271619_b.jpg',
					'images/apartments/Baka/b_apartment1/round-white-and-brown-table-with-four-chairs-2275292_b.jpg',
				],
				mainImage:
					'images/apartments/Baka/b_apartment1/main/living-room-4320373_b.jpg',
				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Baka',
				apartmentNumber: 2,
				room: 2,
				price: 900000,
				sqrM: 200,
				floor: '1 / 4',
				balconies: 0,
				parking: 1,
				roccmended: true,
				attributes: ['Modern'],
				squareFeet: 0,
				images: [
					'images/apartments/Baka/b_apartment2/apartment-architecture-cabinets-chairs-533157_b.jpg',
					'images/apartments/Baka/b_apartment2/white-ceramic-sink-beside-white-ceramic-toilet-bowl-3634742_b.jpg',
				],
				mainImage:
					'images/apartments/Baka/b_apartment2/main/apartment-contemporary-couch-curtains-275484_b.jpg',
				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Baka',
				apartmentNumber: 3,
				room: 4,
				price: 1200000,
				sqrM: 300,
				floor: '2 / 3',
				balconies: 1,
				parking: 1,
				roccmended: true,
				attributes: ['Modern'],
				squareFeet: 0,
				images: [
					'images/apartments/Baka/b_apartment3/arranged-white-bedspread-inside-room-2029687_b.jpg',
					'images/apartments/Baka/b_apartment3/kitchen-and-dining-area-1080721_b.jpg',
					'images/apartments/Baka/b_apartment3/high-raised-building-1330753_b.jpg',
				],
				mainImage:
					'images/apartments/Baka/b_apartment3/main/green-2-seat-sofa-1918291_b.jpg',
				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Baka',
				apartmentNumber: 4,
				room: 4,
				price: 1500000,
				sqrM: 200,
				floor: '4 / 4',
				balconies: 1,
				parking: 1,
				roccmended: true,
				attributes: ['Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Baka/b_apartment4/round-brown-wooden-stool-near-brown-sofa-892618_b.jpg',
					'images/apartments/Baka/b_apartment4/chopping-boards-near-oven-under-hood-2062426_b.jpg',
					'images/apartments/Baka/b_apartment4/bedroom-area-with-no-people-inside-building-2082087_b.jpg',
					'images/apartments/Baka/b_apartment4/white-wooden-shelf-beside-bed-2062431_b.jpg',
					'images/apartments/Baka/b_apartment4/white-and-black-laptop-computer-on-brown-wooden-stool-near-698170_b.jpg',
				],
				mainImage:
					'images/apartments/Baka//b_apartment4/main/round-brown-wooden-table-between-two-chairs-and-ottoman-2079246_b.jpg',
				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Baka',
				apartmentNumber: 5,
				room: 2,
				price: 700000,
				sqrM: 130,
				floor: '2 / 6',
				balconies: 0,
				parking: 0,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Baka/b_apartment5/apartment-bed-bedroom-chair-271618_b.jpg',
					'images/apartments/Baka/b_apartment5/white-ceramic-toilet-bowl-beside-glass-wall-1599790_b.jpg',
				],
				mainImage:
					'images/apartments/Baka/b_apartment5/main/two-chairs-with-glass-table-on-living-room-near-window-1571453_b.jpg',
				broker: {
					brokerName: 'Sara Feldman',
					brokerEmail: 'sarafeldman@.gl.co',
					brokerPhone: '053-3333333',
					brokerImage: 'images/brokers/sara2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Baka',
				apartmentNumber: 6,
				room: 2,
				price: 850000,
				sqrM: 240,
				floor: '4 / 6',
				balconies: 0,
				parking: 1,
				roccmended: true,
				attributes: ['Modern'],
				squareFeet: 0,
				images: [
					'images/apartments/Baka/b_apartment6/candles-contemporary-decoration-furniture-210687_b.jpg',
					'images/apartments/Baka/b_apartment6/white-ceramic-bathtub-near-white-ceramic-bathtub-3288104_b.png',
					'images/apartments/Baka/b_apartment6/green-plants-on-white-concrete-staircase-3639540_b.jpg',
				],
				mainImage:
					'images/apartments/Baka/b_apartment6/main/empty-bedroom-set-1648768_b.png',
				broker: {
					brokerName: 'Tuvia Ahituv',
					brokerEmail: 'tuviaahituv@.gl.co',
					brokerPhone: '054-4444444',
					brokerImage: 'images/brokers/tovia2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Baka',
				apartmentNumber: 7,
				room: 6,
				price: 305000,
				sqrM: 700,
				floor: '1 /1',
				balconies: 2,
				parking: 2,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Baka/b_apartment7/grey-fabric-sectional-sofa-on-brown-wooden-floor-1743226_b.jpg',
					'images/apartments/Baka/b_apartment7/house-table-luxury-lamp-3741314_b.jpg',
					'images/apartments/Baka/b_apartment7/living-room-923129_b.jpg',
					'images/apartments/Baka/b_apartment7/living-room-area-1743228_b.jpg',
					'images/apartments/Baka/b_apartment7/pexels-1643375_b.jpg',
					'images/apartments/Baka/b_apartment7/pexels-3741313_b.jpg',
					'images/apartments/Baka/b_apartment7/photo-of-living-room-1743227_b.jpg',
					'images/apartments/Baka/b_apartment7/purple-blanket-1743231_b.jpg',
				],
				mainImage:
					'images/apartments/Baka/b_apartment7/main/living-room-1668857_b.jpg',
				broker: {
					brokerName: 'Sara Feldman',
					brokerEmail: 'sarafeldman@.gl.co',
					brokerPhone: '053-3333333',
					brokerImage: 'images/brokers/sara2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Katamon',
				apartmentNumber: 1,
				room: 2,
				price: 800000,
				sqrM: 220,
				floor: '2 / 4',
				balconies: 1,
				parking: 1,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Katamon/k_apartment1/white-bed-comforter-during-daytimne-90317_b.jpg',
					'images/apartments/Katamon/k_apartment1/white-ceramic-sink-near-white-bathtub-3958949_b.jpg',
				],
				mainImage:
					'images/apartments/Katamon/k_apartment1/main/rectangular-brown-wooden-dining-table-and-wooden-chairs-3229076_b.jpg',
				broker: {
					brokerName: 'Sara Feldman',
					brokerEmail: 'sarafeldman@.gl.co',
					brokerPhone: '053-3333333',
					brokerImage: 'images/brokers/sara2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Katamon',
				apartmentNumber: 2,
				room: 2,
				price: 700000,
				sqrM: 240,
				floor: '4 / 6',
				balconies: 1,
				parking: 0,
				roccmended: true,
				attributes: ['Modern'],
				squareFeet: 0,
				images: [
					'images/apartments/Katamon/k_apartment2/rectangular-white-island-table-in-kitchen-2398375_b.jpg',
					'images/apartments/Katamon/k_apartment2/plush-toys-on-top-of-white-and-grey-mattress-inside-bedroom-1139784_b.jpg',
				],
				mainImage:
					'images/apartments/Katamon/k_apartment2/main/poodle-lying-on-comfortable-bed-3554424_b.jpg',
				broker: {
					brokerName: 'Sara Feldman',
					brokerEmail: 'sarafeldman@.gl.co',
					brokerPhone: '053-3333333',
					brokerImage: 'images/brokers/sara2.jpg',
				},
			},

			{
				city: 'Jerusalem',
				neighborhood: 'Katamon',
				apartmentNumber: 3,
				room: 4,
				price: 900000,
				sqrM: 400,
				floor: '4 / 6',
				balconies: 1,
				parking: 2,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Katamon/k_apartment3/white-bathroom-toilet-bowl-3316926_b.jpg',
					'images/apartments/Katamon/k_apartment3/white-bed-next-to-white-accent-table-90319_b.jpg',
					'images/apartments/Katamon/k_apartment3/white-wooden-door-on-brown-wooden-parquet-floor-3935314_b.jpg',
				],
				mainImage:
					'images/apartments/Katamon/k_apartment3/main/white-wooden-cupboards-2724749_b.jpg',
				broker: {
					brokerName: 'Sara Feldman',
					brokerEmail: 'sarafeldman@.gl.co',
					brokerPhone: '053-3333333',
					brokerImage: 'images/brokers/sara2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Katamon',
				apartmentNumber: 4,
				room: 2,
				price: 60000,
				sqrM: 200,
				floor: '4 / 5',
				balconies: 1,
				parking: 0,
				roccmended: true,
				attributes: ['Modern'],
				squareFeet: 0,
				images: [
					'images/apartments/Katamon/k_apartment4/apartment-chair-clean-contemporary-279719_b.jpg',
					'images/apartments/Katamon/k_apartment4/apartment-bath-bathroom-bathtub-358592_b.jpg',
				],
				mainImage:
					'images/apartments/Katamon/k_apartment4/main/apartment-architecture-cabinets-chairs-373548_b.jpg',
				broker: {
					brokerName: 'Tuvia Ahituv',
					brokerEmail: 'tuviaahituv@.gl.co',
					brokerPhone: '054-4444444',
					brokerImage: 'images/brokers/tovia2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Katamon',
				apartmentNumber: 5,
				room: 2,
				price: 700000,
				sqrM: 200,
				floor: '4 / 6',

				balconies: 0,
				parking: 0,
				roccmended: true,
				attributes: ['Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Katamon/k_apartment5/black-wooden-table-near-wall-210604_b.jpg',
					'images/apartments/Katamon/k_apartment5/boys-bedroom-3958960_b.jpg',
					'images/apartments/Katamon/k_apartment5/kitchen-4320376_b.jpg',
				],
				mainImage:
					'images/apartments/Katamon/k_apartment5/main/black-flat-screen-tv-turned-off-210265_b.jpg',
				broker: {
					brokerName: 'Tuvia Ahituv',
					brokerEmail: 'tuviaahituv@.gl.co',
					brokerPhone: '054-4444444',
					brokerImage: 'images/brokers/tovia2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Katamon',
				apartmentNumber: 6,
				room: 2,
				price: 85000,
				sqrM: 200,
				floor: '2 / 3',
				balconies: 1,
				parking: 1,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Katamon/k_apartment6/photo-of-bed-near-wooden-cabinet-3935331_b.jpg',
					'images/apartments/Katamon/k_apartment6/white-wooden-modular-kitchen-1643384_b.jpg',
				],
				mainImage:
					'images/apartments/Katamon/k_apartment6/main/photo-of-home-interior-4276607_b.jpg',
				broker: {
					brokerName: 'Tuvia Ahituv',
					brokerEmail: 'tuviaahituv@.gl.co',
					brokerPhone: '054-4444444',
					brokerImage: 'images/brokers/tovia2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Rehavia',
				apartmentNumber: 1,
				room: 4,
				price: 1700000,
				sqrM: 600,
				floor: '4 / 4',
				balconies: 2,
				parking: 2,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Rehavia/r_apartment1/luxury-kitchen-design-cooking-94865_b.jpg',
					'images/apartments/Rehavia/r_apartment1/gray-bed-comforter-3201735_b.jpg',
					'images/apartments/Rehavia/r_apartment1/gray-beddings-3201761_b.jpg',
					'images/apartments/Rehavia/r_apartment1/lighted-pendant-ceiling-lamp-viewing-dining-table-3220528_b.jpg',
					'images/apartments/Rehavia/r_apartment1/messy-bedroom-3626595_b.jpg',
				],
				mainImage:
					'images/apartments/Rehavia/r_apartment1/main/city-road-street-building-3992172_b.jpg',
				broker: {
					brokerName: 'Sara Feldman',
					brokerEmail: 'sarafeldman@.gl.co',
					brokerPhone: '053-3333333',
					brokerImage: 'images/brokers/sara2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Rehavia',
				apartmentNumber: 2,
				room: 1,
				price: 300000,
				sqrM: 200,
				floor: '4 / 6',
				balconies: 0,
				parking: 0,
				roccmended: true,
				attributes: ['Modern'],
				squareFeet: 0,
				images: [
					'images/apartments/Rehavia/r_apartment2/photography-of-bedroom-1034584_b.jpg',
					'images/apartments/Rehavia/r_apartment2/interior-design-of-home-1643383_b.jpg',
				],
				mainImage:
					'images/apartments/Rehavia/r_apartment2/main/kitchen-4320375_b.jpg',

				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Rehavia',
				apartmentNumber: 3,
				room: 1,
				price: 300000,
				sqrM: 200,
				floor: '4 / 6',
				balconies: 0,
				parking: 1,
				roccmended: true,
				attributes: ['Modern'],
				squareFeet: 0,
				images: [
					'images/apartments/Rehavia/r_apartment3/white-wooden-kitchen-cabinet-1599791_b.jpg',
					'images/apartments/Rehavia/r_apartment3/white-ceiling-fan-turned-off-3935340_b.jpg',
				],
				mainImage:
					'images/apartments/Rehavia/r_apartment3/main/used-red-coffee-cup-and-saucer-1648839_b.jpg',
				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Rehavia',
				apartmentNumber: 4,
				room: 3,
				price: 980000,
				sqrM: 500,
				floor: '6 / 8',
				balconies: 2,
				parking: 2,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Rehavia/r_apartment4/apartment-architecture-ceiling-lamp-chairs-269262_b.jpg',
					'images/apartments/Rehavia/r_apartment4/bathroom-cabinet-candles-faucet-342800_b.jpg',
					'images/apartments/Rehavia/r_apartment4/white-wooden-cupboards-2724749_b.jpg',
				],
				mainImage:
					'images/apartments/Rehavia/r_apartment4/main/white-bed-linen-on-bed-3675263_b.jpg',
				broker: {
					brokerName: 'Sara Feldman',
					brokerEmail: 'sarafeldman@.gl.co',
					brokerPhone: '053-3333333',
					brokerImage: 'images/brokers/sara2.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Rehavia',
				apartmentNumber: 5,
				room: 4,
				price: 500000,
				sqrM: 200,
				floor: '4 / 4',
				balconies: 1,
				parking: 1,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Rehavia/r_apartment5/bedroom-1571447_b.jpg',
					'images/apartments/Rehavia/r_apartment5/apartment-architecture-family-floor-276656_b.jpg',
					'images/apartments/Rehavia/r_apartment5/photo-of-bathroom-2088257_b.jpg',
				],
				mainImage:
					'images/apartments/Rehavia/r_apartment5/main/apartment-ceiling-chairs-contemporary-280232_b.jpg',
				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Rehavia',
				apartmentNumber: 6,
				room: 1,
				price: 330000,
				sqrM: 200,
				floor: '2 / 2',
				balconies: 0,
				parking: 0,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Rehavia/r_apartment6/green-leaf-plant-709820_b.jpg',
					'images/apartments/Rehavia/r_apartment6/photo-of-bathroom-3794734_b.jpg',
				],
				mainImage:
					'images/apartments/Rehavia/r_apartment6/main/cabinet-chair-clean-contemporary-259819_b.jpg',
				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
			{
				city: 'Jerusalem',
				neighborhood: 'Rehavia',
				apartmentNumber: 7,
				room: 4,
				price: 800000,
				sqrM: 340,
				floor: '4 / 6',
				balconies: 1,
				parking: 1,
				roccmended: true,
				attributes: ['Modern', 'Innovative'],
				squareFeet: 0,
				images: [
					'images/apartments/Rehavia/r_apartment7/building-construction-house-architecture-2079601_b.jpg',
					'images/apartments/Rehavia/r_apartment7/bedroom-chair-contemporary-furniture-271695_b.jpg',
					'images/apartments/Rehavia/r_apartment7/black-laptop-on-bed-3568792_b.jpg',
				],
				mainImage:
					'images/apartments/Rehavia/r_apartment7/main/photo-of-kitchen-interior-4221390_b.jpg',
				broker: {
					brokerName: 'Barak Ahituv',
					brokerEmail: 'barakahituve@.gl.co',
					brokerPhone: '052-2222222',
					brokerImage: 'images/brokers/barak.jpg',
				},
			},
		],
	});
});

module.exports = router;
